export const GET_VACATIONS = 'GET_VACATIONS';
export const ADD_VACATION = 'ADD_VACATION';
export const DELETE_VACATION = 'DELETE_VACATION';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_VACATION = 'UPDATE_VACATION';
export const FILTER_VACATIONS = 'FILTER_VACATIONS';
export const CLEAR_VACATIONS = 'CLEAR_VACATIONS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const VACATION_ERROR = 'VACATION_ERROR';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

